# Generated by Django 5.2.13 on 2026-06-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('duracion', models.CharField(help_text='Ej. 64 horas, 1 cuatrimestre', max_length=100, verbose_name='Duración')),
                ('profesor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Profesor')),
                ('lugar', models.CharField(blank=True, help_text='Ej. Aula 102, Laboratorio B', max_length=200, null=True, verbose_name='Lugar')),
                ('contenido', models.TextField(blank=True, null=True, verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
    ]
