# Generated by Django 5.2.13 on 2026-06-20 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias', to='profesor.profesor', verbose_name='Profesor'),
        ),
    ]
