# Generated by Django 5.2.13 on 2026-06-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
        ('materias', '0002_alter_materia_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='planes_estudio',
            field=models.ManyToManyField(blank=True, related_name='materias', to='carreras.planestudio', verbose_name='Planes de Estudio'),
        ),
    ]
