# Generated by Django 5.2.13 on 2026-06-20 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='dni',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_dni', message='El DNI solo debe contener números.', regex='^\\d+$')], verbose_name='DNI'),
        ),
    ]
