# Generated by Django 5.2.13 on 2026-06-20 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0002_alter_profesor_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='dni',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI solo puede contener números.', regex='^[0-9]+$')], verbose_name='DNI'),
        ),
    ]
