# Generated by Django 6.1.1 on 2026-09-07 13:21

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0003_alter_profesor_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, unique=True, verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='fecha_contratacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de contratación'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='telefono',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono solo puede contener números, espacios, + o -.', regex='^[0-9+\\-\\s]+$')], verbose_name='Teléfono'),
            preserve_default=False,
        ),
    ]
