# Generated by Django 5.2.13 on 2026-06-20 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesor', '0003_alter_profesor_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Carrera')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Carrera')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carreras_dirigidas', to='profesor.profesor', verbose_name='Director de Carrera')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CargoDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=100, verbose_name='Nombre del Cargo (ej. Director de Tesis)')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('resolucion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Resolución de Designación')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_docentes', to='profesor.profesor', verbose_name='Docente')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_docentes', to='carreras.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Cargo Docente',
                'verbose_name_plural': 'Cargos Docentes',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre/Código del Plan (ej. Plan 2024)')),
                ('año_resolucion', models.PositiveIntegerField(verbose_name='Año de la Resolución')),
                ('is_active', models.BooleanField(default=True, help_text='Define si las nuevas inscripciones a la carrera se realizarán bajo este plan de estudios.', verbose_name='Está Activo')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_estudio', to='carreras.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Plan de Estudio',
                'verbose_name_plural': 'Planes de Estudio',
                'ordering': ['-año_resolucion', 'nombre'],
            },
        ),
    ]
